BibleVerseApplication/Controllers/VerseSearchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BibleVerseApplication.Models;

namespace BibleVerseApplication.Controllers
{
    public class VerseSearchController : Controller
    {
        private MyBibleDatabaseEntities db = new MyBibleDatabaseEntities();

        // GET: VerseSearch
        public ActionResult Search(string searchBy, string search)
        {
            if (searchBy == "Testament")
            {
                return View(db.BibleTables.Where(x => x.TestamentSelection == search || search == null).ToList());
            }
            else
            {
                return View(db.BibleTables.Where(x => x.BookSelection.StartsWith(search) || search == null).ToList());
            }
        }

        // GET: VerseSearch/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BibleTable bibleTable = db.BibleTables.Find(id);
            if (bibleTable == null)
            {
                return HttpNotFound();
            }
            return View(bibleTable);
        }
        // GET: VerseSearch/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BibleTable bibleTable = db.BibleTables.Find(id);
            if (bibleTable == null)
            {
                return HttpNotFound();
            }
            return View(bibleTable);
        }

        // POST: VerseSearch/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BibleId,TestamentSelection,BookSelection,ChapterNumber,VerseNumber,VerseText,DateOfEntry")] BibleTable bibleTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bibleTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Search");
            }
            return View(bibleTable);
        }

        // GET: VerseSearch/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BibleTable bibleTable = db.BibleTables.Find(id);
            if (bibleTable == null)
            {
                return HttpNotFound();
            }
            return View(bibleTable);
        }

        // POST: VerseSearch/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BibleTable bibleTable = db.BibleTables.Find(id);
            db.BibleTables.Remove(bibleTable);
            db.SaveChanges();
            return RedirectToAction("Search");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BibleVerseApplication/Views/VerseSearch/Delete.cshtml
@model BibleVerseApplication.Models.BibleTable

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>This the Deleting form</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Use this form to delete your Verse Entry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TestamentSelection)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestamentSelection)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookSelection)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookSelection)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChapterNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChapterNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VerseNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VerseNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VerseText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VerseText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfEntry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfEntry)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Verse Listing", "VerseListing", "BibleVerse")
        </div>
    }
</div>

BibleVerseApplication/Views/VerseSearch/Details.cshtml
@model BibleVerseApplication.Models.BibleTable

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>BibleTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TestamentSelection)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestamentSelection)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookSelection)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookSelection)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChapterNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChapterNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VerseNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VerseNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VerseText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VerseText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfEntry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfEntry)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BibleId }) |
    @Html.ActionLink("Back to Verse Listing", "VerseListing", "BibleVerse")
</p>

BibleVerseApplication/Views/VerseSearch/Edit.cshtml
@model BibleVerseApplication.Models.BibleTable

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BibleTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BibleId)

        <div class="form-group">
            @Html.LabelFor(model => model.TestamentSelection, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestamentSelection, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestamentSelection, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookSelection, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookSelection, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookSelection, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChapterNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChapterNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChapterNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VerseNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VerseNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VerseNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VerseText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VerseText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VerseText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfEntry, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfEntry, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfEntry, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Verse Listing", "VerseListing", "BibleVerse")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BibleVerseApplication/Views/VerseSearch/Search.cshtml
@model IEnumerable<BibleVerseApplication.Models.BibleTable>

@{
    ViewBag.Title = "Verse Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Welcome to the Bible Verse Search Page</h2>
<h4>Please Select the Search Criteria to begin your search</h4>
<div style="font-family: sans-serif">
    <p>
        @using (Html.BeginForm("Search", "VerseSearch", FormMethod.Get))
        {
            <b>Search By:</b><br/>
            <br/>@Html.RadioButton("SearchBy", "Testament") <text>Testament</text>
            <br/>@Html.RadioButton("SearchBy", "BookName", true ) <text>Book Name</text><br>
            <br/>@Html.TextBox("Search") <input type="submit" value="Search"/>
        }
    </p>
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TestamentSelection)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookSelection)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChapterNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VerseNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VerseText)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfEntry)
            </th>
            <th>User Actions</th>
        </tr>
        @if (!Model.Any())
        {
            <tr>
                <td colspan="7">No Data Matches your Search Criteria</td>
            </tr>

        }
        else
        {

            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TestamentSelection)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookSelection)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ChapterNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VerseNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VerseText)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateOfEntry)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new {id = item.BibleId}) |
                        @Html.ActionLink("Details", "Details", new {id = item.BibleId}) |
                        @Html.ActionLink("Delete", "Delete", new {id = item.BibleId})
                    </td>
                </tr>
            }
        }

    </table>
    <p>
        @Html.ActionLink("Create New Verse", "Create", "BibleVerse") |
        @Html.ActionLink("Back to Search Records", "Search")
    </p>
</div>